### ISSUE TITLE
Will there be scripts for getting the pretrained model weights?

### ISSUE THREAD

**Issue by tingxueronghua** [KU-CVLAB/DreamMatcher#2]
Thanks for your awesome work and effort in making it open-source. 
I am not familiar with this field, but I notice that there are personalized models. I guess getting them still needs some processing. It would be much easier for other researchers to follow your work if there are scripts of how to get them.

Thanks!

**Comment by nam-jisu** [comment]
Hi,

Thank you for your interest in our work. We have provided our baselines (Textual Inversion, DreamBooth, CustomDiffusion) here:  https://drive.google.com/drive/folders/1R2-x8BpqryVTjYBKmafCA6YJ0cLtNi1s?usp=share_link. 

Due to a minor issue, the DreamBooth weights are not fully provided yet, but they will be uploaded by tomorrow. If you have any more questions, feel free to ask us.

**Comment by tingxueronghua** [comment]
Thanks!
